context:
  version: "3.4.1"

package:
  name: pueue
  version: ${{ version }}
  
source:
  url: https://github.com/Nukesor/pueue/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 868710de128db49e0a0c4ddee127dfc0e19b20cbdfd4a9d53d5ed792c5538244

build:
  script:
    - if: unix
      then:
        - cargo install --locked --root $PREFIX --path ./pueue --no-track
      else:
        - cargo install --locked --root %PREFIX% --path ./pueue --no-track

requirements:
  build:
    - ${{ compiler("rust") }}

tests:
  - script:
      - pueue --help
