name: Selective Run

on:
  push:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.16.1
        cache: true
        auth-host: prefix.dev
        auth-token: ${{ secrets.PREFIX_API_KEY }}

    - name: Add .pixi/envs/default to the $PATH
      shell: bash
      run: |
        echo "$(pwd)/.pixi/envs/default/bin" >> $GITHUB_PATH

    - name: Get changed subdirectories
      id: changed-subdirectories
      shell: bash
      run: |
        changed_dirs=$(git diff --name-only HEAD~1 HEAD | grep 'recipe.yaml' | grep -oE '^[^/]+' | uniq | tr '\n' ' ')
        echo "dirs=$changed_dirs" >> $GITHUB_OUTPUT

    - name: Run code in changed subdirectories
      shell: bash
      run: |
        for dir in ${{ steps.changed-subdirectories.outputs.dirs }}; do
          echo "Running code in $dir"
          rattler-build build --recipe $dir/recipe.yaml
        done

    - name: Upload all packages
      shell: bash
      run: |
        # ignore errors because we want to ignore duplicate packages
        for file in output/**/*.conda; do
          rattler-build upload prefix -c rust-forge "$file" || true
        done
