name: Build all packages

on:
  push:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.18.0
        cache: true

    - name: Add .pixi/envs/default to the $PATH
      shell: bash
      run: |
        echo "$(pwd)/.pixi/envs/default/bin" >> $GITHUB_PATH

    - name: Run code in changed subdirectories
      shell: bash
      run: |
        rattler-build build --recipe-dir . --skip-existing=all -c conda-forge -c https://prefix.dev/rust-forge

    - name: Upload all packages
      shell: bash
      env:
        PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
      run: |
        # ignore errors because we want to ignore duplicate packages
        for file in output/**/*.conda; do
          rattler-build upload prefix -c rust-forge "$file" || true
        done
